name: Create ECR Repository
description: Create an ECR Repository if it doesn't exist
inputs:
  repository:
    description: The repository name to create in the ECR registry
    type: string
    required: true
runs:
  using: composite
  steps:
    - run: |
        output=$(aws ecr describe-repositories --repository-names "${{ inputs.repository }}" 2>&1)
        echo $output
        if [ $? -ne 0 ]; then
          if echo ${output} | grep -q RepositoryNotFoundException; then
            aws ecr create-repository --repository-name "${{ inputs.repository }}"
          else
            >&2 echo ${output}
          fi
        fi
      shell: bash
